### ISSUE TITLE
ErrorMessage: TypeError: Cannot read property 'find' of undefined. All changes were discarded.

### ISSUE THREAD

**Issue by Zehke** [satisfactorymodding/SatisfactoryModLauncher#12]
When I press the install-button on a mod, I get the error message and cannot install any mod:
"TypeError: Cannot read property 'find' of undefined. All changes were discarded."

It happens with every mod.

Edit: I accidently discovered some sort of fix: delete the initial "modded"-config via the modlauncher and create a new one.

All mods were installable

**Comment by mircearoata** [comment]
Yes, I am aware of this issue, will release a fix for it in the next hour
