### ISSUE TITLE
Error: Command failed: tasklist

### ISSUE THREAD

**Issue by MarcoN33** [satisfactorymodding/SatisfactoryModLauncher#15]
The command "tasklist" is either misspelled or could not be found.
What is the problem ?
![Unbenannt](https://user-images.githubusercontent.com/46418003/77459995-cefd8d00-6e00-11ea-84d6-34054d7590cb.jpg)

**Comment by mircearoata** [comment]
What windows version are you using?

**Comment by MarcoN33** [comment]
Windows 10 , 64 Bit

**Comment by MarcoN33** [comment]
> Windows 10 , 64 Bit. , new installation of the modloader did not improve

**Comment by MarcoN33** [comment]
Ok, my problem has been solved, the Windows system variable (Path) was defective, entries were missing. After manual maintenance of the variable, the modlauncher now runs.

**Comment by mircearoata** [comment]
I thought something like this would be the issue. Regardless, I changed to a better way of getting the task list

**Comment by mircearoata** [comment]
Replaced tasklist with another method in the latest version so broken Path shouldn't be an issue anymore (might still be for other apps though, so try not to break it)
