### ISSUE TITLE
Installing some mods takes forever

### ISSUE THREAD

**Issue by Blubb98321** [satisfactorymodding/SatisfactoryModLauncher#17]
In my case installing the Area Actions mod quite works for me. But installing the WFurniture mod or some other mods the ModLoader will stuck downloading the mod...
![SML](https://user-images.githubusercontent.com/54849472/77984117-00022400-7311-11ea-8733-5ae5dba964b2.png)

**Comment by mircearoata** [comment]
The latest update includes timeout for downloading in case something goes wrong there, and also another possible fix for this issue

**Comment by Blubb98321** [comment]
it´s fixed for me now, thanks for updating!
