### ISSUE TITLE
getting error when trying to install mod and automatically installs moar factory and utility mod

### ISSUE THREAD

**Issue by sardukar922** [satisfactorymodding/SatisfactoryModLauncher#19]
I have been using the mod launcher for the last couple of weeks and been working great, but today i cannot install any mod or update it. i get the following message:
Error: Ev6vA8A45NfgPk@1.0.0 not found

Another issue is that it always tries to install moar factory and the utility mod each time i run the launcher.  I have to go to the mods section and manually delete the files or the games crashes.

**Comment by mircearoata** [comment]
The issues are kinda linked, you somehow had MoarFactory Resources v1.0.0 installed and it was removed from ficsit.app, and in SMLauncher v1.0.4 it automatically uninstalls versions removed from ficsit.app, but it is broken. I will release a fix for it tomorrow (9h or so)

**Comment by mircearoata** [comment]
Fixed in v1.0.5
