### ISSUE TITLE
Satisfactory need to Kill with Taskmanager

### ISSUE THREAD

**Issue by WtFKilla** [satisfactorymodding/SatisfactoryModLauncher#21]
When i launch the game and play with mods it worked very well, but when i save and click back to desktop the game is running in the background with arround 3,5-4gb of ram must kill it with Taskmgr
Same for a friend i played with

Mod Launcher Version 1.0.5

**Comment by mircearoata** [comment]
This is not related to SMLauncher, it is an issue with SML, but it will be fixed soon™
