### ISSUE TITLE
Satisfactory [Experimental] v119583 Crash

### ISSUE THREAD

**Issue by SatisfactoryBug** [satisfactorymodding/SatisfactoryModLauncher#24]
Satisfactory [Experimental] v119583 Keep Crashing with a pop-up for Send and Close / Send and Restart, It might be bcos of SatisfactoryModLauncher MODs in the SatisfactoryExperimental

Satisfactory [Early Access] v118201 working fine

**Comment by mircearoata** [comment]
This has nothing to do with SMLauncher. The game was updated, so mods will have to be updated.
Currently, mods that crash the game are Light It Up and Refined Power.
The updated project for mods is almost ready, be patient

**Comment by SatisfactoryBug** [comment]
thank for mentioned it so i did remove Light It Up and Refined Power and now working fine, i surprised u know what mod gave a problem as i had 30 mods and would not know which is which is the source of caused
