### ISSUE TITLE
Keeps getting error after 16th April update of game

### ISSUE THREAD

**Issue by Unkickable** [satisfactorymodding/SatisfactoryModLauncher#25]
I installed game through UE4 & after today's update, SML keeps crashing whenever trying to launch

Version: 119646, IsPerforceBuild: false, BuildConfiguration: Shipping, NetMode: 

Assertion failed: ObjectA == nullptr || ObjectA->IsA<UClass>() [File:D:\ws\SB-160502110050-fad\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\PropertyClass.cpp] [Line: 156]

FactoryGame_Win64_Shipping!FWindowsErrorOutputDevice::Serialize() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\windows\windowserroroutputdevice.cpp:79]
FactoryGame_Win64_Shipping!FOutputDevice::LogfImpl() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\outputdevice.cpp:71]
FactoryGame_Win64_Shipping!AssertFailedImplV() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:101]
FactoryGame_Win64_Shipping!FDebug::CheckVerifyFailedImpl() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:439]
FactoryGame_Win64_Shipping!UClassProperty::Identical() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\propertyclass.cpp:156]
FactoryGame_Win64_Shipping!UBlueprintGeneratedClass::BuildCustomPropertyListForPostConstruction() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\blueprintgeneratedclass.cpp:470]
FactoryGame_Win64_Shipping!UBlueprintGeneratedClass::UpdateCustomPropertyListForPostConstruction() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\blueprintgeneratedclass.cpp:608]
FactoryGame_Win64_Shipping!UBlueprintGeneratedClass::SerializeDefaultObject() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\blueprintgeneratedclass.cpp:319]
FactoryGame_Win64_Shipping!FAsyncPackage::EventDrivenSerializeExport() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:3610]
FactoryGame_Win64_Shipping!FAsyncPackage::ProcessImportsAndExports_Event() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:3937]
FactoryGame_Win64_Shipping!<lambda_34eee40e849fa2534d7a680d55b737bd>::operator()() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:2736]
FactoryGame_Win64_Shipping!FAsyncLoadingThread::ProcessAsyncLoading() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4488]
FactoryGame_Win64_Shipping!FAsyncLoadingThread::TickAsyncThread() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:5269]
FactoryGame_Win64_Shipping!FAsyncLoadingThread::Run() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:5196]
FactoryGame_Win64_Shipping!FRunnableThreadWin::Run() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:96]

**Comment by mircearoata** [comment]
Not related to SMLauncher. Coffee Stain again changed the headers considerably, so mods will need updating. Not as much to update as Update 2->Update 3, but still needed. The mods that cause crashes are Refined Power and Light It Up, the other might not work, but probably won't need an update. We are working on updating the headers, it is almost done
