### ISSUE TITLE
After install SatisfactoryModLauncher no buttons in screen

### ISSUE THREAD

**Issue by freakysnake** [satisfactorymodding/SatisfactoryModLauncher#27]
I've tried the "SatisfactoryModLauncher v1.0.6", after the installation i have a strange image.
If i use my other Windows 10 system it work fine. what to i need to fix this issue?

![s_modlauncher_error](https://user-images.githubusercontent.com/63880862/79614823-a87df980-8101-11ea-895f-3c5d93e0c35c.JPG)

**Comment by mircearoata** [comment]
Click View->Toggle Developer Tools, click the console tab and send a screenshot of it

**Comment by freakysnake** [comment]
Hello mircearoata,
this is my screenshot -> console tab

![s_modlauncher_error2](https://user-images.githubusercontent.com/63880862/79633356-3e973b80-8165-11ea-8bb6-feb2dc69e1ec.JPG)

**Comment by mircearoata** [comment]
This has to do with the `#` in the path (https://github.com/electron/electron/issues/4867). I did the fix suggested there and it worked for me. See if it works for you. https://drive.google.com/open?id=1tmumqP1sig8j_vC91g2rx3dqjbC5hpP6

**Comment by freakysnake** [comment]
I had download the file your uploaded to googledrive and it work fine for me. 
 Alternativ i create a new Windows 10 User named "gaming" (without a # in the username). Than it work fine too. Because my Windows 10 username is "#thorsten". 
Thank you for helping mircearoata, good work. Top!!

Screenshot after your fix
![s_modlauncher_fix](https://user-images.githubusercontent.com/63880862/79686236-327fac80-823f-11ea-9aa5-918562c40bbb.JPG)
