### ISSUE TITLE
Not auto-updating

### ISSUE THREAD

**Issue by Wizard17** [satisfactorymodding/SatisfactoryModLauncher#28]
Hi,

FYI
Been anxiously waiting for the 1.0.6 update. Starting the program it anounced it would auto-update at close but that didn't work. It starts 4 processes, at close one process stopped, the remaining 3 just sat there doing nothing. Had to kill them, download the update from here and manually execute it to update.

**Comment by mircearoata** [comment]
The 4 processes is how electron works, one of them was the window, which stopped when you closed it, but the others stayed to download the update and install it.

During the first hour or so from the release, the release was broken (the file name was not the one auto-update expected, which probably made it just do nothing), but it was fixed then (checked myself that it auto-updated, which I did for every other update and I should have done for this one too)

Auto updates do take a while, GitHub's download speed is very slow (500KB/s), so if it shows network activity, let it do it's thing

**Comment by Wizard17** [comment]
The 3 processes were not doing anything. I've probably been just to quick like you say... np. Manually worked just fine aswell :-)
