### ISSUE TITLE
my mods don't work properly

### ISSUE THREAD

**Issue by Herbertti** [satisfactorymodding/SatisfactoryModLauncher#29]
So i downloaded some mods and they only work in one save. and i can't figure out why. in the save i see them in the hub upgrade thing but when i change save they don't show up

**Comment by Herbertti** [comment]
so does anybody know the issue??

**Comment by mircearoata** [comment]
If you are on experimental it is an issue with the mod loader, it doesn't work that well on experimental yet, new version is coming soon.

Also, be patient, you posted the issue, commented again, and closed it within minutes, consider the fact that not everyone is in your timezone (I was sleeping at that time)
