### ISSUE TITLE
Cannot start Early Access 118201 with mods

### ISSUE THREAD

**Issue by Snoddas76** [satisfactorymodding/SatisfactoryModLauncher#31]
Hi,
I have been using SML 1.0.5 without getting an auto-update. Just now i started SML again to install some mods for the latest Experimental version. That worked fine and also to start the game.

But, when i then try to start Early Access again, SML causes the game to crash and saying "SML requires at least CL-119583":
![SML 118201 crash](https://user-images.githubusercontent.com/25012168/80021625-1304b000-84db-11ea-8a29-73de69b3213c.png)

The problem is that the latest Early Access version IS 118201. The 119583 version number is on Experimental.

I now tried to update SML to 1.0.9 manually, thinking that might be the problem. But when i start SML again, the program asks me to update and when i do that, it says "Game version incompatible. Installed: 118201. bootstrapper requires >= 117050, SML requires >= 119805 All changes were discarded."
![SML 118201 start error](https://user-images.githubusercontent.com/25012168/80021632-1730cd80-84db-11ea-9b1e-5a9c69e56392.png)

When i remove that message, SML is open and says on the Help menu that the version is 1.0.9. But, i still get the same error trying to start Early Access and i also get the update question now every time i start SML. Oh and i also can't remove any mods using SML, it says the same thing about the Game version not being compatible.

**Comment by mircearoata** [comment]
Switch to the vanilla config and back to the modded config so that it installs the right SML version

**Comment by Snoddas76** [comment]
> 
> 
> Switch to the vanilla config and back to the modded config so that it installs the right SML 

That worked beautifully! When i switched back to modded and restarted SML, i saw that it sad version 2.0.0 instead of 2.1.0 for Early Access and i could re-install all the mods and launch the game just fine. Thank you :)
