### ISSUE TITLE
no mods listed

### ISSUE THREAD

**Issue by garywilson4** [satisfactorymodding/SatisfactoryModLauncher#36]
opened sml tonight and something has broke since this afternoon
this is the view i get on opening
SatisfactoryModLauncher v1.0.13
tried reinstall
tried reboot
tried going back a version (same issue) and updating

![Screenshot_1](https://user-images.githubusercontent.com/36335413/80850817-da20b580-8c15-11ea-868b-1dfe38b3456e.jpg)

**Comment by kane-2020** [comment]
same issue. did the exact same attempts to resolve to no avail.

**Comment by mircearoata** [comment]
Fixed in v1.0.14
