### ISSUE TITLE
storage.ficsit.app blocked by my AV - Trojan detected!

### ISSUE THREAD

**Issue by electric-node** [satisfactorymodding/SatisfactoryModLauncher#37]
Ever since update 1.0.13 SML (storage.ficsit.app) has been flagged as a Trojan source by my antivirus and Windows 10 SmartSafe warns me of risk when installing an app with unknown publisher.

**Comment by Vilsol** [comment]
What antivirus are you using, and are you able to simply view the site and download files using your browser?

**Comment by electric-node** [comment]
I use Malwarebytes. It blocks the web site in all 4 browsers I have installed, 2 browsers say SSL error.
On my iPad, the site gets redirected to backblaze.com - a cloud storage service.

**Comment by budak7273** [comment]
Would you be able to provide the protection logs and/or screenshots of what Malwarebytes shows you when it blocks the site? They request that information for reporting a false positive.

There is supposedly information [here](https://forums.malwarebytes.com/topic/200068-please-read-before-posting-a-possible-fp/) on how to get the protection logs, but the image refuses to load for me.

**Comment by electric-node** [comment]
I have reported a possible FP to Malwarebytes.

[SML-Trojan detected.txt](https://github.com/satisfactorymodding/SatisfactoryModLauncher/files/4571776/SML-Trojan.detected.txt)

**Comment by budak7273** [comment]
Thanks!

For future readers of this issue, the post on the Malwarebytes forums is [here](https://forums.malwarebytes.com/topic/259319-new-possible-fp-storageficsitapp/).

**Comment by budak7273** [comment]
@electric-node Do you know if the block has since been removed? I have not heard any more reports of Malwarebytes issues occurring, but I'd like to be sure before I close the issue.

**Comment by electric-node** [comment]
@budak7273 I have not herd from Malwarebytes but after removing "storage.ficsit.app" from Malwarebytes allowed list, SML loads with no issues.

Thanks for your assistance :)
