### ISSUE TITLE
When you click a link in a mod description it opens the link in the launcher and there is now way back.

### ISSUE THREAD

**Issue by jdoxley** [satisfactorymodding/SatisfactoryModLauncher#4]
![image](https://user-images.githubusercontent.com/25972715/76571869-d3778c80-6475-11ea-9ce2-537d00eb5fb6.png)

**Comment by mircearoata** [comment]
This is fixed in the next version (today maybe)

**Comment by mircearoata** [comment]
Fixed in 1.0.2
