### ISSUE TITLE
Incompatibility with 121119

### ISSUE THREAD

**Issue by zAAmpie** [satisfactorymodding/SatisfactoryModLauncher#40]
Just to track the issue, the new experimental build broke the mod subsystem. Switching to vanilla works fine.

Thanks for the effort!

**Comment by GeoffreyEmerson** [comment]
Is this to be expected on every update?

**Comment by zAAmpie** [comment]
Fair point, though I don't believe all updates break the launcher this significantly, i.e. game crashes instantly?

Or am I mistaken?

**Comment by mircearoata** [comment]
It is not an issue with the launcher, but with SML (mod loader). Not all updates break it, but since the game doesn't know what SML needs, it might leave out some stuff when it is compiled. And when this happens, SML needs to adapt to that.

**Comment by zAAmpie** [comment]
> It is not an issue with the launcher, but with SML (mod loader). Not all updates break it, but since the game doesn't know what SML needs, it might leave out some stuff when it is compiled. And when this happens, SML needs to adapt to that.

Apologies. I only looked at how the project was split after I posted. Are these issues useful to note, i.e. to prompt that there was an update that breaks SML? Or do you get notified in the Discord?

**Comment by mircearoata** [comment]
We usually check relatively quick if everything still works, but even if we don't, the discord is filled with messages asking why it doesn't work, in case that happens

**Comment by zAAmpie** [comment]
Then doing it here is probably redundant. Thanks for the effort though - amazing work! I'll close this then.

**Comment by FiRem00** [comment]
This is still broken for me. Game loads in EXP, stays black, then crashes to desktop. Even after SML goes to 2.1.1

**Comment by Wizard17** [comment]
I had the same. First make sure all mods are up to date (I had to update "Programmable Elevators". Then switch to Vanilla. Launch Game (Don't know if necessary, but I did). Quit Game. Switch back to Modded and luanch Game. That worked for me...

**Comment by mircearoata** [comment]
If you updated very soon after SML 2.1.1 was released, you didn't get the latest bootstrapper version which was uploaded 30min or so later. Switching to vanilla and back to modded should make it refresh and get the latest version, and if it doesn't, removing all mods and adding then back should.

Will make SMLauncher display bootstrapper updates, so this isn't needed, soon

**Comment by FiRem00** [comment]
Ahh yes, that looks like what it was. It didn't automatically update the bootstrapper, I had to manually download them. Adding that updating would be a nice addition as you say :D Thanks both. :)
