### ISSUE TITLE
it happened again

### ISSUE THREAD

**Issue by garywilson4** [satisfactorymodding/SatisfactoryModLauncher#41]
same issue as before happened again 

![Screenshot_21](https://user-images.githubusercontent.com/36335413/81238592-5b9f8b80-8ffa-11ea-8677-3c656f4d822c.jpg)

**Comment by mircearoata** [comment]
Click Help->Toggle Debug, then restart SMLauncher and send console log

**Comment by garywilson4** [comment]
it fixed not long after
