### ISSUE TITLE
sml dosen't detect satisfactory from steam

### ISSUE THREAD

**Issue by Myran04** [satisfactorymodding/SatisfactoryModLauncher#46]
it seems to not detect my satisfactory

**Comment by bjornthv** [comment]
> it seems to not detect my satisfactory

I think it would be a good solution to be able to add the satisfactory location manually and/or add Steam Location detection. Caveat that should be noted is that Steam allows locations on other drives; in my case I have a separate disk/volume allocated to games. This however could be solved simply by allowing the possibility to enter/locate the game manually.

**Comment by mircearoata** [comment]
See issue #44
