### ISSUE TITLE
Error: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by Iwan1803** [satisfactorymodding/SatisfactoryModLauncher#5]
SatisfactoryModLauncher v1.0.1
I tried to install "Area Actions", but doesn't work:

> Error: EBUSY: resource busy or locked, open 'S:\Epic Games\SatisfactoryEarlyAccess\loaders\UE4-SML-Win64-Shipping.dll'. All changes were discarded.

What does that mean? The game is not running in the background. I tried it with and without admin rights.

**Comment by Iwan1803** [comment]
I deleted the mentioned file, installed the mod again and now it seems to be working.

**Comment by sardukar922** [comment]
what file did yall delete to get it working? also could i get the link to the discord?

**Comment by Iwan1803** [comment]
I deleted only the file from the error message:
`S:\Epic Games\SatisfactoryEarlyAccess\loaders\UE4-SML-Win64-Shipping.dll`

**Comment by mircearoata** [comment]
The link to the discord is in the readme. I think I found the reason this error happens, and it might be fixed in the next version

**Comment by mircearoata** [comment]
Should be fixed in 1.0.2. If the error still happens, please reopen this issue
