### ISSUE TITLE
It can't fing my game

### ISSUE THREAD

**Issue by picasso2010** [satisfactorymodding/SatisfactoryModLauncher#8]
Is there any way to set the path to the games exe file ?

**Comment by SuperCoder7979** [comment]
No. If you have bought the game on epic, it should automatically find your game location.

**Comment by hamdiayoub7** [comment]
Is there any way to set the path to the games exe file  on cracked one ?

**Comment by SuperCoder7979** [comment]
No. Buy the game.

**Comment by hamdiayoub7** [comment]
but its 3.5x money for me so i have to pay 85$ :(

**Comment by lagarantie** [comment]
I've bought the game but it cant find the game. Any idea

**Comment by mircearoata** [comment]
It would be easier to solve this on discord, because the responses will be quicker.

Open SMLauncher, press ctrl+shift+i, console tab, and send a screenshot
